# version: '3.3'
services:
  app:
    container_name: 'bookmaker'
    depends_on:
      - 'mongo'
    build: .
    # image: bookmaker ##"514095112279.dkr.ecr.eu-central-1.amazonaws.com/bookmaker:latest"  
    ports:
      - '9099:9099'
    volumes:
      - .:/app
    tty: true
    restart: unless-stopped
    networks:
      - main  
      - db


  static:
    container_name: 'nginx'
    depends_on:
      - 'app'
    image: 'nginx:latest' #nginx:1.23.3
    ports:
      - '80:80'
    # entrypoint: "nginx -c /etc/nginx/nginx.conf"
    volumes:
      - ./nginx/dev.conf.d:/etc/nginx/conf.d
      # - "./app/static:/usr/share/nginx/html"
      # - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    tty: true
    restart: unless-stopped     
    networks: 
      - main

  db:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - db
  
networks:
  main:
    name: main
  second:
    name: db
  