# x-env: &env
#   environment:
#     - serverPort

x-def: &def
  tty: true
  restart: unless-stopped


# version: '3.3'
services:
  app:
    container_name: 'bookmaker'
    # depends_on:
    #   - 'db'
    build: .
    # image: bookmaker ##"514095112279.dkr.ecr.eu-central-1.amazonaws.com/bookmaker:latest"  
    # ports:
    #   - '9090:9090'
    volumes:
      - ./app:/app
    networks:
      - main  
      - db
    <<: *def


  static:
    container_name: 'nginx'
    depends_on:
      - 'app'
    image: 'nginx:latest' #nginx:1.23.3
    ports:
      - '80:80'
    # entrypoint: "nginx -c /etc/nginx/conf.d"
    volumes:
      - './nginx/dev.conf.d:/etc/nginx/conf.d'
      # - './app/static:/usr/share/nginx/html'
      # - './nginx/dev.conf.d:/etc/nginx/nginx.conf'
    networks: 
      - main
    <<: *def


  db:
    image: 'mongo:latest'
    container_name: 'mongo'
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - db
  
networks:
  main:
    name: main
  db:
    name: db
  