# x-env: &env
#   environment:
#     - serverPort

x-def: &def
  tty: true
  restart: unless-stopped

services:
  app:
    container_name: 'bookmaker'
    depends_on:
      - 'db'
    build: ./app
    # ports:
    #   - '9090:9090'
    volumes:
      - ./app:/app
    networks:
      - app  
      - db
    <<: *def


  static:
    container_name: 'nginx'
    depends_on:
      - 'app'
    image: 'nginx:latest' #nginx:1.23.3
    ports:
      - '80:80'
    # entrypoint: "nginx -c /etc/nginx/conf.d"
    volumes:
      - './nginx/dev.conf.d:/etc/nginx/conf.d'
      # - './app/static:/usr/share/nginx/html'
      # - './nginx/dev.conf.d:/etc/nginx/nginx.conf'
    networks: 
      - app
    <<: *def

  db:
    image: 'mongo:latest'
    container_name: 'mongo'
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - db
  
networks:
  app:
    name: app
  db:
    name: db
  