apiVersion: v1
kind: Secret
metadata:
  name: {{ include "BM.fullname" . }}-mongo
type: Opaque
data:
  user: {{ required "mongo user name is required!" .Values.mongodb.auth.rootUser | b64enc }} #ZHZpcm9zcw== #dviross
  pass: {{ required "mongo pass name is required!" .Values.mongodb.auth.rootPassword | b64enc }} #c2VjcmV0cGFzcw== #secretpass
  MONGODB_URI: bW9uZ29kYjovLyQodXNlcik6JChwYXNzKUAkKHJlbGVhc2UpLW1vbmdvZGItMC4kKHNlcnZpY2UpLCQocmVsZWFzZSktbW9uZ29kYi0xLiQoc2VydmljZSksJChyZWxlYXNlKS1tb25nb2RiLTIuJChzZXJ2aWNlKS8/cmVwbGljYVNldD1yczA=
  #mongodb://$(user):$(pass)@$(release)-mongodb-0.$(service),$(release)-mongodb-1.$(service),$(release)-mongodb-2.$(service)/?replicaSet=rs0
  