# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mongodb
# spec:
#   serviceName: mongodb
#   replicas: 3
#   selector:
#     matchLabels:
#       app: mongodb
#   template:
#     metadata:
#       labels:
#         app: mongodb
#     spec:
#       containers:
#       - name: mongodb
#         image: mongo:4.4.0
#         ports:
#         - containerPort: 27017
#           name: mongodb
#         volumeMounts:
#         - name: mongodb-persistent-storage
#           mountPath: /data/db
#       volumes:
#       - name: mongodb-persistent-storage
#         persistentVolumeClaim:
#           claimName: mongodb-pvc
