# root = "./"
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "task default"
  bin = "./tmp/main"
  full_bin = ""

  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  args_bin = [] #["hello", "world"]
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  
  kill_delay = "0s" #500 # ms
  # Rerun binary or not
  rerun = false
  # Delay after each executions
  rerun_delay = 500
  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false