apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory
  name: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artifactory
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/main: "true"
        io.kompose.service: artifactory
    spec:
      containers:
        - image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
          name: artifactory
          ports:
            - containerPort: 8081
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/opt/jfrog/artifactory
              name: artifactory-data
      restartPolicy: Always
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-data
status: {}
