apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: dev
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/main: "true"
        io.kompose.service: dev
    spec:
      containers:
        - args:
            - sleep
            - inf
          image: maven:3.8.7-openjdk-18-slim
          name: dev
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /root/.m2
              name: dev-claim0
            - mountPath: /dvir
              name: dev-claim1
            - mountPath: /root/.ssh
              name: dev-claim2
          workingDir: /lab
      restartPolicy: Always
      volumes:
        - name: dev-claim0
          persistentVolumeClaim:
            claimName: dev-claim0
        - name: dev-claim1
          persistentVolumeClaim:
            claimName: dev-claim1
        - name: dev-claim2
          persistentVolumeClaim:
            claimName: dev-claim2
status: {}
