apiVersion: v1
name: bookmaker
description: chart for bookmaker app
type: application


version: 1.0.0
appVersion: 1.0.0

# dependencies:
#   - name: mongodb
#     version: 13.5.0
#     repository: "https://charts.bitnami.com/bitnami"